### ISSUE TITLE
Bed leveling

### ISSUE THREAD

**Issue by Sibert** [rpanfili/sk200#4]
I'm looking to convert a Zortrax M200 to klipper, but I'm only looking to change out the main board, not the rest of the hardware. Most of the process seems straightforward to me, but the only thing I'm unsure of, is if (and how) the bed probing would work. Could you shine some light on how/if it can be done?

**Comment by rpanfili** [comment]
Yes, it's absolutely possible to change only the mainboard and use the original bed probing system. For example you may use a [pullup resistor](https://learn.sparkfun.com/tutorials/pull-up-resistors/all) on the wire connected to the nozzle and gnd on the bed: when nozzle touches the bed it close the circuit so you get low level signal, high otherwise.

**Comment by Sibert** [comment]
Hmm I expected it to be some continuity type circuit but I couldn't find a pin connected to the nozzle. The nozzle is somewhat dirty tho so that may have been the cause. Thanks

**Comment by rpanfili** [comment]
Yes, you have to check electric continuity on the nozzle. Especially if you use custom pieces like me you may need to create an anchor point for you nozzle signal, like in this photo.
![IMG_7207](https://user-images.githubusercontent.com/1826444/141788664-e7db34b5-6b1e-4e23-9da1-eef5630d76c5.jpg)
